INSERT INTO place (name, image_url) VALUES ('Cloud Dragon Temple', 'https://img1.goodfon.com/wallpaper/nbig/3/c2/art-gory-hram-drakon-aziya.jpg');
INSERT INTO place (name, image_url) VALUES ('Camp', 'https://p4.wallpaperbetter.com/wallpaper/646/350/481/anime-laid-back-camp-nadeshiko-kagamihara-rin-shima-wallpaper-preview.jpg');
INSERT INTO place (name, image_url) VALUES ('Villa of the Dead', 'https://www.teahub.io/photos/full/230-2306914_anime-ghost-city.jpg');
INSERT INTO place (name, image_url) VALUES ('Sanctuary of Last Gasp', 'https://a-static.besthdwallpaper.com/puerta-torii-del-santuario-tradicional-papel-pintado-1024x768-62947_18.jpg');
INSERT INTO place (name, image_url) VALUES ('Incident Town', 'https://uploads.spiritfanfiction.com/fanfics/capitulos/201710/rei-arthur-10685812-181020172152.jpg');
INSERT INTO place (name, image_url) VALUES ('Jubilation Graveyard', 'https://i.pinimg.com/originals/66/db/4c/66db4c1540e84f1f2a1ed0dc73de93b8.jpg');
INSERT INTO place (name, image_url) VALUES ('The Island', 'https://pbs.twimg.com/media/EMbD3wRXkAAzSdG.jpg');
INSERT INTO place (name, image_url) VALUES ('Endless start', 'https://p4.wallpaperbetter.com/wallpaper/324/214/446/anime-statue-field-horse-wallpaper-preview.jpg');

INSERT INTO body_part (name) VALUES ('Skin');
INSERT INTO body_part (name) VALUES ('Left Leg');
INSERT INTO body_part (name) VALUES ('Right eye');
INSERT INTO body_part (name) VALUES ('Vocal chords/voice');
INSERT INTO body_part (name) VALUES ('Ears/hearing');
INSERT INTO body_part (name) VALUES ('Right Arm');
INSERT INTO body_part (name) VALUES ('Esophagus');
INSERT INTO body_part (name) VALUES ('Platelets');
INSERT INTO body_part (name) VALUES ('Trapezius Muscles');
INSERT INTO body_part (name) VALUES ('Kidneys');
INSERT INTO body_part (name) VALUES ('Ears');
INSERT INTO body_part (name) VALUES ('Lymph Nodes');
INSERT INTO body_part (name) VALUES ('Pancreas');
INSERT INTO body_part (name) VALUES ('Cerebral Neo-cortex');
INSERT INTO body_part (name) VALUES ('Hippocampal Synapse');
INSERT INTO body_part (name) VALUES ('Abdominal muscles');
INSERT INTO body_part (name) VALUES ('Nose');
INSERT INTO body_part (name) VALUES ('Ribs');
INSERT INTO body_part (name) VALUES ('Bone Marrow');
INSERT INTO body_part (name) VALUES ('Minotaur');
INSERT INTO body_part (name) VALUES ('Adrenal Glands');
INSERT INTO body_part (name) VALUES ('Cerebellum');
INSERT INTO body_part (name) VALUES ('Small Intestines');
INSERT INTO body_part (name) VALUES ('Sense of Pain');
INSERT INTO body_part (name) VALUES ('Left eye');
INSERT INTO body_part (name) VALUES ('Teeth');
INSERT INTO body_part (name) VALUES ('Spine');
INSERT INTO body_part (name) VALUES ('Right Leg');
INSERT INTO body_part (name) VALUES ('Sense of touch');
INSERT INTO body_part (name) VALUES ('Large Intestines');
INSERT INTO body_part (name) VALUES ('Lungs');
INSERT INTO body_part (name) VALUES ('Skull');
INSERT INTO body_part (name) VALUES ('Liver');
INSERT INTO body_part (name) VALUES ('Thyroid glands');
INSERT INTO body_part (name) VALUES ('Pectoral Muscles');
INSERT INTO body_part (name) VALUES ('Heart');
INSERT INTO body_part (name) VALUES ('Lateral Muscles');


INSERT INTO demon (name, defeat, image_url, place_id, body_part_id) VALUES ('Deiki', false, 'https://static.wikia.nocookie.net/dororo/images/4/4d/Deiki.png', 1, 1);
INSERT INTO demon (name, defeat, image_url, place_id, body_part_id) VALUES ('Bandai', false, 'https://static.wikia.nocookie.net/dororo/images/9/9b/Bandai_human.png', 1, 2);
INSERT INTO demon (name, defeat, image_url, place_id, body_part_id) VALUES ('Nihil', false, 'https://static.wikia.nocookie.net/dororo/images/3/39/Nihil_%28Anime%29.png', 1, 3);
INSERT INTO demon (name, defeat, image_url, place_id, body_part_id) VALUES ('Kajirinkon', false, 'https://static.wikia.nocookie.net/dororo/images/2/21/Kyubi_%28Anime%29.png', 1, 4);
INSERT INTO demon (name, defeat, image_url, place_id, body_part_id) VALUES ('Silver vine tree demon', false, 'https://static.wikia.nocookie.net/dororo/images/4/45/Hakumenfudo_anime.png', 1, 5);
INSERT INTO demon (name, defeat, image_url, place_id, body_part_id) VALUES ('Nue', false, 'https://static.wikia.nocookie.net/dororo/images/1/1c/Nue.png', 2, 6);
INSERT INTO demon (name, defeat, image_url, place_id, body_part_id) VALUES ('Hellcrusher', false, 'https://static.wikia.nocookie.net/dororo/images/8/8f/Midoro_anime.png', 2, 7);
INSERT INTO demon (name, defeat, image_url, place_id, body_part_id) VALUES ('Grave Golem', false, 'https://static.wikia.nocookie.net/dororo/images/c/c6/Arijigoku_%28Anime%29.png', 2, 8);
INSERT INTO demon (name, defeat, image_url, place_id, body_part_id) VALUES ('Inquisitor', false, 'https://i.pinimg.com/originals/c9/31/62/c93162678ee28066d4e1da3fd377e960.jpg', 2, 9);
INSERT INTO demon (name, defeat, image_url, place_id, body_part_id) VALUES ('Giant Fire Wheel', false, 'https://i.imgur.com/ieTWPiQ.jpg', 2, 10);
INSERT INTO demon (name, defeat, image_url, place_id, body_part_id) VALUES ('Twin Blade', false, 'https://i.pinimg.com/originals/61/8c/b9/618cb9ff3c03e5dc1dade99811235d34.jpg', 2, 11);
INSERT INTO demon (name, defeat, image_url, place_id, body_part_id) VALUES ('Three-Tailed Fox', false, 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSgokuYaCbu4_l-EiafopEQAvkcC3vjRXawUw&usqp=CAU', 3, 12);
INSERT INTO demon (name, defeat, image_url, place_id, body_part_id) VALUES ('Six-Tailed Fox', false, 'https://www.cultture.com/pics/2019/09/5-anime-de-terror-que-te-asustara-tontamente-y-5-que-no-asustara-a-nadie-0.jpg', 3, 13);
INSERT INTO demon (name, defeat, image_url, place_id, body_part_id) VALUES ('Beast Fiend', false, 'https://i.pinimg.com/736x/83/7a/20/837a205c4615aa9c81dc7ea5d8d01155.jpg', 3, 14);
INSERT INTO demon (name, defeat, image_url, place_id, body_part_id) VALUES ('Dreameater', false, 'https://www.nacionrex.com/__export/1567277745947/sites/debate/img/2019/08/31/moms16_main_crop1567277745601.jpg_423682103.jpg', 3, 15);
INSERT INTO demon (name, defeat, image_url, place_id, body_part_id) VALUES ('Wind Fiend', false, 'https://cde.peru.com//ima/0/0/9/3/5/935828/924x530/zona-asia.jpg', 3, 16);
INSERT INTO demon (name, defeat, image_url, place_id, body_part_id) VALUES ('Legion', false, 'https://deanime.es/wp-content/uploads/2016/08/Shiki-e1539904912743.jpg', 4, 17);
INSERT INTO demon (name, defeat, image_url, place_id, body_part_id) VALUES ('Blood Ape', false, 'https://i0.wp.com/pollotaku.com/wp-content/uploads/2020/04/yami-shibai-pollotaku.jpg?fit=1000%2C667&ssl=1', 4, 18);
INSERT INTO demon (name, defeat, image_url, place_id, body_part_id) VALUES ('Giant Inferno Wheel', false, 'https://k-magazinemx.com/wp-content/uploads/2019/10/Top-anime-terror-e1572416963940.png.webp', 4, 19);
INSERT INTO demon (name, defeat, image_url, place_id, body_part_id) VALUES ('Minotaur', false, 'https://i.blogs.es/6af668/horror-japones/1366_2000.jpg', 4, 20);
INSERT INTO demon (name, defeat, image_url, place_id, body_part_id) VALUES ('Goliath', false, 'https://static.wikia.nocookie.net/dororo/images/e/ef/LizardDemon.png', 5, 21);
INSERT INTO demon (name, defeat, image_url, place_id, body_part_id) VALUES ('Night Terror', false, 'https://static.wikia.nocookie.net/dororo/images/2/22/Nokosaregumo.png', 5, 22);
INSERT INTO demon (name, defeat, image_url, place_id, body_part_id) VALUES ('Gaping Maw', false, 'https://static.wikia.nocookie.net/dororo/images/4/4f/Jiromaru.png', 5, 23);
INSERT INTO demon (name, defeat, image_url, place_id, body_part_id) VALUES ('Mountainous', false, 'https://deanime.es/wp-content/uploads/2016/08/Yami_Shibai-e1539905166547.jpg', 5, 24);
INSERT INTO demon (name, defeat, image_url, place_id, body_part_id) VALUES ('Donburibara', false, 'https://tse2.mm.bing.net/th?id=OIP.J61S-wygd23Vv5zxM-dIBQHaEK&pid=Api', 6, 25);
INSERT INTO demon (name, defeat, image_url, place_id, body_part_id) VALUES ('Birabira', false, 'https://static.wikia.nocookie.net/dororo/images/5/52/Asura.png', 6, 26);
INSERT INTO demon (name, defeat, image_url, place_id, body_part_id) VALUES ('Spider demon', false, 'https://4.bp.blogspot.com/-qptsh8UEnz4/WpjtJYsD_sI/AAAAAAAAAmk/2KcnsbRrteIKQxdf8OE3iFltxGj0josIACLcBGAs/s1600/f742a709e1b1e4ddcd55f3a35e446c51494f6700_hq.jpg', 6, 27);
INSERT INTO demon (name, defeat, image_url, place_id, body_part_id) VALUES ('Maimai-onba', false, 'https://static.wikia.nocookie.net/dororo/images/1/10/Maimai-onba_as_human.png', 6, 28);
INSERT INTO demon (name, defeat, image_url, place_id, body_part_id) VALUES ('Shike Nyuudou', false, 'https://peru21.pe/resizer/_0nQnt8ER-gH_LKwwqaQS0ZmyaA=/1200x800/smart/filters:format(jpeg):quality(75)/arc-anglerfish-arc2-prod-elcomercio.s3.amazonaws.com/public/5VX6772BFBHGDMTNAWBTUMUI2M.jpg', 6, 29);
INSERT INTO demon (name, defeat, image_url, place_id, body_part_id) VALUES ('Soul Stealer', false, 'https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/mejores-anime-terror-junji-ito-collection-1537889553.jpg', 7, 30);
INSERT INTO demon (name, defeat, image_url, place_id, body_part_id) VALUES ('Demon Ogress', false, 'https://i0.wp.com/www.freim.tv/wp-content/uploads/2021/08/Junji-Ito-1.jpg', 7, 31);
INSERT INTO demon (name, defeat, image_url, place_id, body_part_id) VALUES ('White Dragon', false, 'https://cdn.superaficionados.com/imagenes/ghost-hound.jpg', 7, 32);
INSERT INTO demon (name, defeat, image_url, place_id, body_part_id) VALUES ('Draconus', false, 'https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/mejores-anime-terror-yami-shibai-2-1537889864.jpg?crop=1.00xw:0.892xh;0,0.0494xh&resize=480:*', 8, 33);
INSERT INTO demon (name, defeat, image_url, place_id, body_part_id) VALUES ('Death', false, 'https://cinematicos.net/wp-content/uploads/l-intro-1622828923.jpg', 8, 34);
INSERT INTO demon (name, defeat, image_url, place_id, body_part_id) VALUES ('Boar Fiend', false, 'https://ilarge.lisimg.com/image/14291251/853full-kakurenbo-screenshot.jpg', 8, 35);
INSERT INTO demon (name, defeat, image_url, place_id, body_part_id) VALUES ('Nine-Tailed Fox', false, 'https://cdn.hobbyconsolas.com/sites/navi.axelspringer.es/public/media/image/2018/10/yami-shibai_0.jpg', 8, 36);
INSERT INTO demon (name, defeat, image_url, place_id, body_part_id) VALUES ('Thunder Fiend', false, 'https://media.airedesantafe.com.ar/adjuntos/268/migration/app/uploads/2019/07/2-2.jpg', 8, 37);

INSERT INTO dororo_character (name, gender, image_url) VALUES ('Dororo','FEMALE','https://3.bp.blogspot.com/-4NAe0ji0CpI/XMwXqT9eWzI/AAAAAAAAAKI/OxBxA6iwOOIv0G_FKp3JRhoFuttiZe0-gCEwYBhgL/s1600/dororo.jpg');

INSERT INTO power (description, dororo_character_id) VALUES ('Agility',1);
INSERT INTO power (description, dororo_character_id) VALUES ('Intellect',1);
INSERT INTO power (description, dororo_character_id) VALUES ('Marksmanship',1);
INSERT INTO power (description, dororo_character_id) VALUES ('Sonic Scream',1);
INSERT INTO power (description, dororo_character_id) VALUES ('Stealth',1);
INSERT INTO power (description, dororo_character_id) VALUES ('Unarmed Combat',1);

INSERT INTO artefact (name, origin, dororo_character_id) VALUES ('sword','STOLEN',1);
INSERT INTO artefact (name, origin, dororo_character_id) VALUES ('sack of coins','OWN',1);
INSERT INTO artefact (name, origin, dororo_character_id) VALUES ('necklace','STOLEN',1);
INSERT INTO artefact (name, origin, dororo_character_id) VALUES ('book','STOLEN',1);
INSERT INTO artefact (name, origin, dororo_character_id) VALUES ('bread','OWN',1);
INSERT INTO artefact (name, origin, dororo_character_id) VALUES ('wine','STOLEN',1);
INSERT INTO artefact (name, origin, dororo_character_id) VALUES ('clothes','OWN',1);
INSERT INTO artefact (name, origin, dororo_character_id) VALUES ('water','OWN',1);
INSERT INTO artefact (name, origin, dororo_character_id) VALUES ('knife','STOLEN',1);
INSERT INTO artefact (name, origin, dororo_character_id) VALUES ('hat','OWN',1);
