INSERT INTO place (name, image_url) VALUES ('Cloud Dragon Temple', 'art-gory-hram-drakon-aziya.jpg');
INSERT INTO place (name, image_url) VALUES ('Camp', 'anime-laid-back-camp-nadeshiko-kagamihara-rin-shima-wallpaper-preview.jpg');
INSERT INTO place (name, image_url) VALUES ('Villa of the Dead', '1637445236177.jpg');
INSERT INTO place (name, image_url) VALUES ('Sanctuary of Last Gasp', '1637446275299.jpg');
INSERT INTO place (name, image_url) VALUES ('Incident Town', 'rei-arthur-10685812-181020172152.jpg');
INSERT INTO place (name, image_url) VALUES ('Jubilation Graveyard', '66db4c1540e84f1f2a1ed0dc73de93b8.jpg');
INSERT INTO place (name, image_url) VALUES ('The Island', 'EMbD3wRXkAAzSdG.jpg');
INSERT INTO place (name, image_url) VALUES ('Endless start', 'anime-statue-field-horse-wallpaper-preview.jpg');

INSERT INTO body_part (name) VALUES ('Skin');
INSERT INTO body_part (name) VALUES ('Left Leg');
INSERT INTO body_part (name) VALUES ('Right eye');
INSERT INTO body_part (name) VALUES ('Vocal chords/voice');
INSERT INTO body_part (name) VALUES ('Ears/hearing');
INSERT INTO body_part (name) VALUES ('Right Arm');
INSERT INTO body_part (name) VALUES ('Esophagus');
INSERT INTO body_part (name) VALUES ('Platelets');
INSERT INTO body_part (name) VALUES ('Trapezius Muscles');
INSERT INTO body_part (name) VALUES ('Kidneys');
INSERT INTO body_part (name) VALUES ('Ears');
INSERT INTO body_part (name) VALUES ('Lymph Nodes');
INSERT INTO body_part (name) VALUES ('Pancreas');
INSERT INTO body_part (name) VALUES ('Cerebral Neo-cortex');
INSERT INTO body_part (name) VALUES ('Hippocampal Synapse');
INSERT INTO body_part (name) VALUES ('Abdominal muscles');
INSERT INTO body_part (name) VALUES ('Nose');
INSERT INTO body_part (name) VALUES ('Ribs');
INSERT INTO body_part (name) VALUES ('Bone Marrow');
INSERT INTO body_part (name) VALUES ('Minotaur');
INSERT INTO body_part (name) VALUES ('Adrenal Glands');
INSERT INTO body_part (name) VALUES ('Cerebellum');
INSERT INTO body_part (name) VALUES ('Small Intestines');
INSERT INTO body_part (name) VALUES ('Sense of Pain');
INSERT INTO body_part (name) VALUES ('Left eye');
INSERT INTO body_part (name) VALUES ('Teeth');
INSERT INTO body_part (name) VALUES ('Spine');
INSERT INTO body_part (name) VALUES ('Right Leg');
INSERT INTO body_part (name) VALUES ('Sense of touch');
INSERT INTO body_part (name) VALUES ('Large Intestines');
INSERT INTO body_part (name) VALUES ('Lungs');
INSERT INTO body_part (name) VALUES ('Skull');
INSERT INTO body_part (name) VALUES ('Liver');
INSERT INTO body_part (name) VALUES ('Thyroid glands');
INSERT INTO body_part (name) VALUES ('Pectoral Muscles');
INSERT INTO body_part (name) VALUES ('Heart');
INSERT INTO body_part (name) VALUES ('Lateral Muscles');


INSERT INTO demon (name, defeat, image_url, place_id, body_part_id) VALUES ('Deiki', false, 'Deiki.png', 1, 1);
INSERT INTO demon (name, defeat, image_url, place_id, body_part_id) VALUES ('Bandai', false, 'Bandai_human.png', 1, 2);
INSERT INTO demon (name, defeat, image_url, place_id, body_part_id) VALUES ('Nihil', false, 'Nihil_28Anime29.jpg', 1, 3);
INSERT INTO demon (name, defeat, image_url, place_id, body_part_id) VALUES ('Kajirinkon', false, 'Kyubi_28Anime29.jpg', 1, 4);
INSERT INTO demon (name, defeat, image_url, place_id, body_part_id) VALUES ('Silver vine tree demon', false, 'Hakumenfudo_anime.png', 1, 5);
INSERT INTO demon (name, defeat, image_url, place_id, body_part_id) VALUES ('Nue', false, 'Nue.png', 2, 6);
INSERT INTO demon (name, defeat, image_url, place_id, body_part_id) VALUES ('Hellcrusher', false, 'Midoro_anime.png', 2, 7);
INSERT INTO demon (name, defeat, image_url, place_id, body_part_id) VALUES ('Grave Golem', false, 'Arijigoku_28Anime29.png', 2, 8);
INSERT INTO demon (name, defeat, image_url, place_id, body_part_id) VALUES ('Inquisitor', false, 'c93162678ee28066d4e1da3fd377e960.jpg', 2, 9);
INSERT INTO demon (name, defeat, image_url, place_id, body_part_id) VALUES ('Giant Fire Wheel', false, 'ieTWPiQ.jpg', 2, 10);
INSERT INTO demon (name, defeat, image_url, place_id, body_part_id) VALUES ('Twin Blade', false, '618cb9ff3c03e5dc1dade99811235d34.jpg', 2, 11);
INSERT INTO demon (name, defeat, image_url, place_id, body_part_id) VALUES ('Three-Tailed Fox', false, 'images.jpg', 3, 12);
INSERT INTO demon (name, defeat, image_url, place_id, body_part_id) VALUES ('Six-Tailed Fox', false, '5-anime-de-terror-que-te-asustara-tontamente-y-5-que-no-asustara-a-nadie-0.jpg', 3, 13);
INSERT INTO demon (name, defeat, image_url, place_id, body_part_id) VALUES ('Beast Fiend', false, '837a205c4615aa9c81dc7ea5d8d01155.jpg', 3, 14);
INSERT INTO demon (name, defeat, image_url, place_id, body_part_id) VALUES ('Dreameater', false, 'moms16_main_crop1567277745601.jpg_423682103.jpg', 3, 15);
INSERT INTO demon (name, defeat, image_url, place_id, body_part_id) VALUES ('Wind Fiend', false, 'zona-asia.jpg', 3, 16);
INSERT INTO demon (name, defeat, image_url, place_id, body_part_id) VALUES ('Legion', false, 'Shiki-e1539904912743.jpg', 4, 17);
INSERT INTO demon (name, defeat, image_url, place_id, body_part_id) VALUES ('Blood Ape', false, 'yami-shibai-pollotaku.jpg', 4, 18);
INSERT INTO demon (name, defeat, image_url, place_id, body_part_id) VALUES ('Giant Inferno Wheel', false, 'Top-anime-terror-e1572416963940.png.jpg', 4, 19);
INSERT INTO demon (name, defeat, image_url, place_id, body_part_id) VALUES ('Minotaur', false, '1366_2000.jpg', 4, 20);
INSERT INTO demon (name, defeat, image_url, place_id, body_part_id) VALUES ('Goliath', false, 'LizardDemon.png', 5, 21);
INSERT INTO demon (name, defeat, image_url, place_id, body_part_id) VALUES ('Night Terror', false, 'Nokosaregumo.png', 5, 22);
INSERT INTO demon (name, defeat, image_url, place_id, body_part_id) VALUES ('Gaping Maw', false, 'Jiromaru.png', 5, 23);
INSERT INTO demon (name, defeat, image_url, place_id, body_part_id) VALUES ('Mountainous', false, 'Yami_Shibai-e1539905166547.jpg', 5, 24);
INSERT INTO demon (name, defeat, image_url, place_id, body_part_id) VALUES ('Donburibara', false, 'th.jpg', 6, 25);
INSERT INTO demon (name, defeat, image_url, place_id, body_part_id) VALUES ('Birabira', false, 'Asura.png', 6, 26);
INSERT INTO demon (name, defeat, image_url, place_id, body_part_id) VALUES ('Spider demon', false, 'f742a709e1b1e4ddcd55f3a35e446c51494f6700_hq.jpg', 6, 27);
INSERT INTO demon (name, defeat, image_url, place_id, body_part_id) VALUES ('Maimai-onba', false, 'Maimai-onba_as_human.png', 6, 28);
INSERT INTO demon (name, defeat, image_url, place_id, body_part_id) VALUES ('Shike Nyuudou', false, '5VX6772BFBHGDMTNAWBTUMUI2M.jpg', 6, 29);
INSERT INTO demon (name, defeat, image_url, place_id, body_part_id) VALUES ('Soul Stealer', false, 'mejores-anime-terror-junji-ito-collection-1537889553.jpg', 7, 30);
INSERT INTO demon (name, defeat, image_url, place_id, body_part_id) VALUES ('Demon Ogress', false, 'Junji-Ito-1.jpg', 7, 31);
INSERT INTO demon (name, defeat, image_url, place_id, body_part_id) VALUES ('White Dragon', false, 'ghost-hound.jpg', 7, 32);
INSERT INTO demon (name, defeat, image_url, place_id, body_part_id) VALUES ('Draconus', false, 'mejores-anime-terror-yami-shibai-2-1537889864.jpg', 8, 33);
INSERT INTO demon (name, defeat, image_url, place_id, body_part_id) VALUES ('Death', false, 'l-intro-1622828923.jpg', 8, 34);
INSERT INTO demon (name, defeat, image_url, place_id, body_part_id) VALUES ('Boar Fiend', false, '853full-kakurenbo-screenshot.jpg', 8, 35);
INSERT INTO demon (name, defeat, image_url, place_id, body_part_id) VALUES ('Nine-Tailed Fox', false, 'yami-shibai_0.jpg', 8, 36);
INSERT INTO demon (name, defeat, image_url, place_id, body_part_id) VALUES ('Thunder Fiend', false, '2-2.jpg', 8, 37);

INSERT INTO dororo_character (name, gender, image_url) VALUES ('Dororo','FEMALE','dororo.jpg');

INSERT INTO power (description, dororo_character_id) VALUES ('Agility',1);
INSERT INTO power (description, dororo_character_id) VALUES ('Intellect',1);
INSERT INTO power (description, dororo_character_id) VALUES ('Marksmanship',1);
INSERT INTO power (description, dororo_character_id) VALUES ('Sonic Scream',1);
INSERT INTO power (description, dororo_character_id) VALUES ('Stealth',1);
INSERT INTO power (description, dororo_character_id) VALUES ('Unarmed Combat',1);

INSERT INTO artefact (name, origin, dororo_character_id) VALUES ('sword','STOLEN',1);
INSERT INTO artefact (name, origin, dororo_character_id) VALUES ('sack of coins','OWN',1);
INSERT INTO artefact (name, origin, dororo_character_id) VALUES ('necklace','STOLEN',1);
INSERT INTO artefact (name, origin, dororo_character_id) VALUES ('book','STOLEN',1);
INSERT INTO artefact (name, origin, dororo_character_id) VALUES ('bread','OWN',1);
INSERT INTO artefact (name, origin, dororo_character_id) VALUES ('wine','STOLEN',1);
INSERT INTO artefact (name, origin, dororo_character_id) VALUES ('clothes','OWN',1);
INSERT INTO artefact (name, origin, dororo_character_id) VALUES ('water','OWN',1);
INSERT INTO artefact (name, origin, dororo_character_id) VALUES ('knife','STOLEN',1);
INSERT INTO artefact (name, origin, dororo_character_id) VALUES ('hat','OWN',1);
